// <auto-generated />
using FantasyPitchXI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FantasyPitchXI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514125443_AddFantasyTeamLineup")]
    partial class AddFantasyTeamLineup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("FantasyPitchXI.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Club");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Arsenal"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chelsea"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bournemouth"
                        });
                });

            modelBuilder.Entity("FantasyPitchXI.Models.FantasyTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Budget")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TransferAvailableThisGameweek")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamName")
                        .IsUnique();

                    b.ToTable("FantasyTeam");
                });

            modelBuilder.Entity("FantasyPitchXI.Models.FantasyTeamLineup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenchOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gameweek")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCaptain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsStarting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsViceCaptain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FantasyTeamId", "PlayerId", "Gameweek")
                        .IsUnique();

                    b.ToTable("FantasyTeamLineups", t =>
                        {
                            t.HasCheckConstraint("CK_Captain_Vice", "NOT ([IsCaptain] = 1 AND [IsViceCaptain] = 1)");
                        });
                });

            modelBuilder.Entity("FantasyPitchXI.Models.FantasyTeamPlayer", b =>
                {
                    b.Property<int>("FantasyTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FantasyTeamId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("FantasyTeamPlayer");
                });

            modelBuilder.Entity("FantasyPitchXI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClubId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("FantasyPitchXI.Models.FantasyTeamLineup", b =>
                {
                    b.HasOne("FantasyPitchXI.Models.FantasyTeamPlayer", "FantasyTeamPlayer")
                        .WithMany("FantasyTeamLineups")
                        .HasForeignKey("FantasyTeamId", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyTeamPlayer");
                });

            modelBuilder.Entity("FantasyPitchXI.Models.FantasyTeamPlayer", b =>
                {
                    b.HasOne("FantasyPitchXI.Models.FantasyTeam", "FantasyTeam")
                        .WithMany("FantasyTeamPlayers")
                        .HasForeignKey("FantasyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyPitchXI.Models.Player", "Player")
                        .WithMany("FantasyTeamPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FantasyTeam");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("FantasyPitchXI.Models.Player", b =>
                {
                    b.HasOne("FantasyPitchXI.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FantasyPitchXI.Models.Club", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FantasyPitchXI.Models.FantasyTeam", b =>
                {
                    b.Navigation("FantasyTeamPlayers");
                });

            modelBuilder.Entity("FantasyPitchXI.Models.FantasyTeamPlayer", b =>
                {
                    b.Navigation("FantasyTeamLineups");
                });

            modelBuilder.Entity("FantasyPitchXI.Models.Player", b =>
                {
                    b.Navigation("FantasyTeamPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
